on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: pkware.azurecr.io
        username: ${{ secrets.acr_pkware_username }}
        password: ${{ secrets.acr_pkware_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t pkware.azurecr.io/openxpki:${{ github.sha }}
        docker push pkware.azurecr.io/openxpki:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_openxpki_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep openxpki5fc7 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace openxpki5fc7`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: openxpki5fc7
        container-registry-url: pkware.azurecr.io
        container-registry-username: ${{ secrets.acr_pkware_username }}
        container-registry-password: ${{ secrets.acr_pkware_password }}
        secret-name: openxpkidockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: openxpki5fc7
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          pkware.azurecr.io/openxpki:${{ github.sha }}
        imagepullsecrets: |
          openxpkidockerauth